<?php
$title = 'Edit Album';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url(
    'album',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="panel panel-primary" style="width: 500px; margin: 0 auto;">
    <div class="panel-heading">
        <div class="panel-title">
            <?=$this->escapeHtml($title);?>
        </div>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <?= $this->formRow($form->get('title')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($form->get('artist')); ?>
        </div>
    </div>
    <div class="panel-footer" style="text-align: center;">
        <?= $this->formHidden($form->get('id')); ?>
        <?= $this->formSubmit($form->get('submit')); ?>
        <a href="<?php echo $this->url('album'); ?>" class="btn btn-default" title="Back">Back</a>
    </div>
</div>
<?= $this->form()->closeTag(); ?>
